key "rndc-key" {
    algorithm hmac-sha256;
    secret "rWoat/UauGjELiit9A3PpBip7NqtOXui0Hghu6RiePk=";
};

options {
    default-key "rndc-key";
    default-server 172.25.0.2;
    default-port 953;
};
